server:
  port: 9494
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payment_test
    username: postgres
    password: j@vacefer2005
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml


feign:
  clients:
    ms-product:
      url: http://localhost:9999


logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG