version: '3.3'
services:
  postgres-payment:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'j@vacefer2005'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'payment'
    ports:
      - '1736:5432'
    volumes:
      - payment-db:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - '6292:8080'

volumes:
  payment-db:
